(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['about'] = template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  return "<div class=\"about\">\n  <img src=\"img/about_bg.jpg\">\n  <h1>About</h1>\n  <p>Robert Bob Bagler was born in Boston in 1951; after years of working in his father`s restaurant, Arthur`s, he struck out on his own in 1979 and started Bob`s Bagels right where it sits today, at XYZ Ave in Boston. For the last forty years, Bob`s Bagels has strived to proved the best bagels in town, at the best prices, made with love from only the freshest ingredients. Bob still works the counter, just like the old days, so stop in sometime and say hello!</p>\n</div>\n";
  },"useData":true});
templates['home'] = template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  return "<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\n  <!-- Indicators -->\n  <ol class=\"carousel-indicators\">\n    <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\n  </ol>\n  <div class=\"carousel-inner\">\n    <div class=\"item active\">\n    <img class=\"carousel-img\" src=\"img/main_bg.jpg\">\n      <div class=\"container\">\n        <div class=\"carousel-caption\">\n          <h1>Welcome to Bob's Bagels!</h1>\n          <p>BEST BAGELS. BEST PRICES. FRESHEST INGREDIENTS. ALL MADE WITH LOVE.</p>\n        </div>\n      </div>\n    </div>\n\n\n";
},"useData":true});
templates['menu'] = template({"1":function(depth0,helpers,partials,data) {
  var stack1, helper, options, functionType="function", helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression, blockHelperMissing=helpers.blockHelperMissing, buffer = "                              <li class=\"menu-type\">"
    + escapeExpression(((helper = (helper = helpers.name || (depth0 != null ? depth0.name : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"name","hash":{},"data":data}) : helper)))
    + "\n                                  <ul id=\"list\">\n";
  stack1 = ((helper = (helper = helpers.menu_items || (depth0 != null ? depth0.menu_items : depth0)) != null ? helper : helperMissing),(options={"name":"menu_items","hash":{},"fn":this.program(2, data),"inverse":this.noop,"data":data}),(typeof helper === functionType ? helper.call(depth0, options) : helper));
  if (!helpers.menu_items) { stack1 = blockHelperMissing.call(depth0, stack1, options); }
  if (stack1 != null) { buffer += stack1; }
  return buffer + "                                  </ul>\n                              </li>\n";
},"2":function(depth0,helpers,partials,data) {
  var helper, functionType="function", helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression;
  return "                                      <li><a class=\"menu-item\"  data-id=\""
    + escapeExpression(((helper = (helper = helpers.id || (depth0 != null ? depth0.id : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"id","hash":{},"data":data}) : helper)))
    + "\" href=\"#\">"
    + escapeExpression(((helper = (helper = helpers.name || (depth0 != null ? depth0.name : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"name","hash":{},"data":data}) : helper)))
    + "</a><span class=\"price\"> "
    + escapeExpression(((helper = (helper = helpers.price || (depth0 != null ? depth0.price : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"price","hash":{},"data":data}) : helper)))
    + "</span></li>\n";
},"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var stack1, buffer = "<div id=\"threefourth-menu\" class=\"item three_fourth\">\n      <img src=\"img/menu2_bg.jpg\" alt=\"\" class=\"fullBg\">\n        <div class=\"content\">\n        <div class=\"content_overlay_three_fourth\"></div>\n          <div class=\"content_inner\">\n            <div class=\"row contentscroll\">\n              <div class=\"container\">\n              <div class=\"col-md-3 empty\">&nbsp;</div>\n                <div class=\"col-md-9 content_text\">\n                  <h1>Menu</h1>\n                    <div class=\"clearfix pad_top13\">\n                      <div class=\"col-md-7\">\n                        <p class=\"row\">\n                          <span class=\"bold\">Yummy sandwiches!</span><br/><br/>\n\n                          <ul id=\"menu-list\">\n";
  stack1 = helpers.each.call(depth0, (depth0 != null ? depth0.menu : depth0), {"name":"each","hash":{},"fn":this.program(1, data),"inverse":this.noop,"data":data});
  if (stack1 != null) { buffer += stack1; }
  return buffer + "                          </ul>\n                        </p>\n                      </div>\n\n\n                      <div class=\"col-md-5\">\n                        <div class=\"right_content \">\n                        <div class=\"sub_title\">\n                          <h4>Opening hours:</h4>\n                        </div>\n                          <div class=\"hour_table\">\n                            <table>\n                              <tr>\n                                <td class=\"days\">mon - Fri</td>\n                                <td>9:00am - 4:00pm</td>\n                              </tr>\n                              <tr>\n                                <td class=\"days\">Sat</td>\n                                <td>9:00am - 2:00pm</td>\n                              </tr>\n                              <tr>\n                                <td class=\"days\">Sun</td>\n                                <td>8:30am - 1:00pm</td>\n                              </tr>\n                            </table>\n                          </div>\n                          <div class=\"sub_title\">\n                            <h4>book your table:</h4>\n                          </div>\n                          <p>We welcome walk-in guests,online at<br/><br><a class=\"button nav-link\" href=\"#reservation\">Book table</a></p>\n                        </div>\n                      </div>\n                    </div>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n    </div>\n";
},"useData":true});
})();
